# Generated by Django 5.0 on 2023-12-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidatesfavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatesFavorite',
        ),
    ]
