# Generated by Django 5.0 on 2023-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_candidatesfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
